2023-04-10 17:01:25,987 - root - ERROR - Faild to open sklearn.txt from logger.error
Traceback (most recent call last):
  File "justscore_bySection_4urldata_final.py", line 234, in main
    response = requests.get(url,verify=False)
  File "D:\Anaconda3\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\Anaconda3\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Anaconda3\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Anaconda3\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "D:\Anaconda3\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "D:\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "D:\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "D:\Anaconda3\lib\site-packages\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "D:\Anaconda3\lib\site-packages\urllib3\connection.py", line 500, in _connect_tls_proxy
    return ssl_wrap_socket(
  File "D:\Anaconda3\lib\site-packages\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "D:\Anaconda3\lib\site-packages\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "D:\Anaconda3\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\Anaconda3\lib\ssl.py", line 997, in _create
    raise ValueError("check_hostname requires server_hostname")
ValueError: check_hostname requires server_hostname
2023-04-10 17:01:45,944 - numexpr.utils - INFO - NumExpr defaulting to 4 threads.
2023-04-10 17:01:46,295 - root - INFO - -2.618783614323712
2023-04-10 17:01:46,298 - root - INFO - corrcoef: 
0.9860095208474686   0.9175757164761829
2023-04-10 17:01:46,304 - root - INFO - regression coefficients:
[[ 1.11042346  0.10271851]
 [-0.09980373  0.98216601]]
2023-04-10 17:01:46,305 - root - INFO - regression intercept:
[-0.46769042 -0.32181783]
2023-04-10 17:01:46,506 - root - ERROR - Faild to open sklearn.txt from logger.error
Traceback (most recent call last):
  File "justscore_bySection_4urldata_final.py", line 337, in main
    img=plt.imread(str(designPth)+"1.png")         # reading backgram photos with png format
  File "D:\Anaconda3\lib\site-packages\matplotlib\pyplot.py", line 2246, in imread
    return matplotlib.image.imread(fname, format)
  File "D:\Anaconda3\lib\site-packages\matplotlib\image.py", line 1496, in imread
    with img_open(fname) as image:
  File "D:\Anaconda3\lib\site-packages\PIL\ImageFile.py", line 109, in __init__
    self.fp = open(fp, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\zc\\ET\\gaze_preprocessing\\utiles\\design1.png'
2023-04-10 17:06:01,185 - numexpr.utils - INFO - NumExpr defaulting to 4 threads.
2023-04-10 17:06:01,737 - root - INFO - -2.618783614323712
2023-04-10 17:06:01,746 - root - INFO - corrcoef: 
0.9860095208474686   0.9175757164761829
2023-04-10 17:06:01,775 - root - INFO - regression coefficients:
[[ 1.11042346  0.10271851]
 [-0.09980373  0.98216601]]
2023-04-10 17:06:01,790 - root - INFO - regression intercept:
[-0.46769042 -0.32181783]
2023-04-10 17:06:01,923 - root - ERROR - Faild to open sklearn.txt from logger.error
Traceback (most recent call last):
  File "justscore_bySection_4urldata_final.py", line 337, in main
    img=plt.imread(str(designPth)+"1.png")         # reading backgram photos with png format
  File "D:\Anaconda3\lib\site-packages\matplotlib\pyplot.py", line 2246, in imread
    return matplotlib.image.imread(fname, format)
  File "D:\Anaconda3\lib\site-packages\matplotlib\image.py", line 1496, in imread
    with img_open(fname) as image:
  File "D:\Anaconda3\lib\site-packages\PIL\ImageFile.py", line 109, in __init__
    self.fp = open(fp, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\zc\\ET\\gaze_preprocessing\\utiles\\design\\1.png'
2023-04-10 17:07:53,707 - numexpr.utils - INFO - NumExpr defaulting to 4 threads.
2023-04-10 17:07:54,018 - root - INFO - -2.618783614323712
2023-04-10 17:07:54,019 - root - INFO - corrcoef: 
0.9860095208474686   0.9175757164761829
2023-04-10 17:07:54,020 - root - INFO - regression coefficients:
[[ 1.11042346  0.10271851]
 [-0.09980373  0.98216601]]
2023-04-10 17:07:54,021 - root - INFO - regression intercept:
[-0.46769042 -0.32181783]
2023-04-10 17:07:56,096 - root - INFO - question:2 	 score:0.9481865284974094
2023-04-10 17:07:58,750 - root - INFO - question:3 	 score:0.1953259532595326
2023-04-10 17:08:01,530 - root - INFO - question:4 	 score:0.26083697688944407
2023-04-10 17:08:04,928 - root - INFO - question:5 	 score:0.3562375745526839
2023-04-10 17:08:08,014 - root - INFO - question:6 	 score:0.024356732450662003
2023-04-10 17:08:10,213 - root - INFO - question:7 	 score:0.3497376967274544
2023-04-10 17:08:12,590 - root - INFO - question:8 	 score:0.2743142144638404
2023-04-10 17:08:14,945 - root - INFO - question:9 	 score:0.30414688983262556
2023-04-10 17:08:17,233 - root - INFO - question:10 	 score:0.18073927555940167
2023-04-10 17:08:20,253 - root - INFO - question:11 	 score:0.28206732574145915
2023-04-10 17:08:24,989 - root - INFO - Plotting succeed.
2023-04-10 17:09:21,924 - numexpr.utils - INFO - NumExpr defaulting to 4 threads.
2023-04-10 17:09:22,333 - root - INFO - -2.793
2023-04-10 17:09:22,334 - root - INFO - corrcoef: 
0.9817181545583858   0.9779883690723026
2023-04-10 17:09:22,336 - root - INFO - regression coefficients:
[[ 0.98902535 -0.10963473]
 [-0.03037846  0.90503259]]
2023-04-10 17:09:22,337 - root - INFO - regression intercept:
[-0.02714035 -0.77552654]
2023-04-10 17:09:24,662 - root - INFO - question:2 	 score:0.9405815423514539
2023-04-10 17:09:26,784 - root - INFO - question:3 	 score:0.10279790157381964
2023-04-10 17:09:28,758 - root - INFO - question:4 	 score:0.9216837371971022
2023-04-10 17:09:30,716 - root - INFO - question:5 	 score:0.951286535098676
2023-04-10 17:09:32,685 - root - INFO - question:6 	 score:0.843472829481574
2023-04-10 17:09:34,625 - root - INFO - question:7 	 score:0.627529352985261
2023-04-10 17:09:36,594 - root - INFO - question:8 	 score:0.7962292421026346
2023-04-10 17:09:39,896 - root - INFO - question:9 	 score:0.7234015984015985
2023-04-10 17:09:44,449 - root - INFO - question:10 	 score:0.5825109306683323
2023-04-10 17:09:47,087 - root - INFO - question:11 	 score:0.22988361907145538
2023-04-10 17:09:48,971 - root - INFO - Plotting succeed.
2023-04-10 17:13:23,209 - numexpr.utils - INFO - NumExpr defaulting to 4 threads.
2023-04-10 17:13:23,525 - root - INFO - -2.793
2023-04-10 17:13:23,526 - root - INFO - corrcoef: 
0.9817181545583858   0.9779883690723026
2023-04-10 17:13:23,528 - root - INFO - regression coefficients:
[[ 0.98902535 -0.10963473]
 [-0.03037846  0.90503259]]
2023-04-10 17:13:23,528 - root - INFO - regression intercept:
[-0.02714035 -0.77552654]
2023-04-10 17:13:25,219 - root - INFO - question:2 	 score:0.9405815423514539
2023-04-10 17:13:26,654 - root - INFO - question:3 	 score:0.10279790157381964
2023-04-10 17:13:28,145 - root - INFO - question:4 	 score:0.9216837371971022
2023-04-10 17:13:29,601 - root - INFO - question:5 	 score:0.951286535098676
2023-04-10 17:13:31,098 - root - INFO - question:6 	 score:0.843472829481574
2023-04-10 17:13:32,518 - root - INFO - question:7 	 score:0.627529352985261
2023-04-10 17:13:33,997 - root - INFO - question:8 	 score:0.7962292421026346
2023-04-10 17:13:35,414 - root - INFO - question:9 	 score:0.7234015984015985
2023-04-10 17:13:36,890 - root - INFO - question:10 	 score:0.5825109306683323
2023-04-10 17:13:38,323 - root - INFO - question:11 	 score:0.22988361907145538
2023-04-10 17:13:39,901 - root - INFO - Plotting succeed.
2023-04-10 18:06:20,155 - numexpr.utils - INFO - NumExpr defaulting to 4 threads.
2023-04-10 18:06:20,584 - root - INFO - -2.793
2023-04-10 18:06:20,584 - root - INFO - corrcoef: 
0.9817181545583858   0.9779883690723026
2023-04-10 18:06:20,586 - root - INFO - regression coefficients:
[[ 0.98902535 -0.10963473]
 [-0.03037846  0.90503259]]
2023-04-10 18:06:20,586 - root - INFO - regression intercept:
[-0.02714035 -0.77552654]
2023-04-10 18:06:22,805 - root - INFO - question:2 	 score:0.9405815423514539
2023-04-10 18:06:22,976 - root - ERROR - Faild to open sklearn.txt from logger.error
Traceback (most recent call last):
  File "justscore_bySection_4urldata_final.py", line 321, in main
    bez_x, bez_y = bezier_pts(time[0], time[-1])
  File "justscore_bySection_4urldata_final.py", line 86, in bezier_pts
    time = np.linspace(start_time/1000, end_time/1000, 1/70)
  File "<__array_function__ internals>", line 5, in linspace
  File "D:\Anaconda3\lib\site-packages\numpy\core\function_base.py", line 113, in linspace
    num = operator.index(num)
TypeError: 'float' object cannot be interpreted as an integer
2023-04-10 18:09:16,258 - numexpr.utils - INFO - NumExpr defaulting to 4 threads.
2023-04-10 18:09:16,629 - root - INFO - -2.793
2023-04-10 18:09:16,630 - root - INFO - corrcoef: 
0.9817181545583858   0.9779883690723026
2023-04-10 18:09:16,633 - root - INFO - regression coefficients:
[[ 0.98902535 -0.10963473]
 [-0.03037846  0.90503259]]
2023-04-10 18:09:16,634 - root - INFO - regression intercept:
[-0.02714035 -0.77552654]
2023-04-10 18:09:18,511 - root - INFO - question:2 	 score:0.9405815423514539
2023-04-10 18:09:21,143 - root - INFO - question:3 	 score:0.10279790157381964
2023-04-10 18:09:25,117 - root - INFO - question:4 	 score:0.9216837371971022
2023-04-10 18:09:28,237 - root - INFO - question:5 	 score:0.951286535098676
2023-04-10 18:09:30,080 - root - INFO - question:6 	 score:0.843472829481574
2023-04-10 18:09:32,152 - root - INFO - question:7 	 score:0.627529352985261
2023-04-10 18:09:34,241 - root - INFO - question:8 	 score:0.7962292421026346
2023-04-10 18:09:36,088 - root - INFO - question:9 	 score:0.7234015984015985
2023-04-10 18:09:37,863 - root - INFO - question:10 	 score:0.5825109306683323
2023-04-10 18:09:39,804 - root - INFO - question:11 	 score:0.22988361907145538
2023-04-10 18:09:41,889 - root - INFO - Plotting succeed.
2023-04-10 18:11:05,515 - numexpr.utils - INFO - NumExpr defaulting to 4 threads.
2023-04-10 18:11:06,104 - root - INFO - -2.618783614323712
2023-04-10 18:11:06,143 - root - INFO - corrcoef: 
0.9860095208474686   0.9175757164761829
2023-04-10 18:11:06,170 - root - INFO - regression coefficients:
[[ 1.11042346  0.10271851]
 [-0.09980373  0.98216601]]
2023-04-10 18:11:06,182 - root - INFO - regression intercept:
[-0.46769042 -0.32181783]
2023-04-10 18:11:08,051 - root - INFO - question:2 	 score:0.9481865284974094
2023-04-10 18:11:10,044 - root - INFO - question:3 	 score:0.1953259532595326
2023-04-10 18:11:12,195 - root - INFO - question:4 	 score:0.26083697688944407
2023-04-10 18:11:14,217 - root - INFO - question:5 	 score:0.3562375745526839
2023-04-10 18:11:16,216 - root - INFO - question:6 	 score:0.024356732450662003
2023-04-10 18:11:18,258 - root - INFO - question:7 	 score:0.3497376967274544
2023-04-10 18:11:20,118 - root - INFO - question:8 	 score:0.2743142144638404
2023-04-10 18:11:21,930 - root - INFO - question:9 	 score:0.30414688983262556
2023-04-10 18:11:23,771 - root - INFO - question:10 	 score:0.18073927555940167
2023-04-10 18:11:25,566 - root - INFO - question:11 	 score:0.28206732574145915
2023-04-10 18:11:27,350 - root - INFO - Plotting succeed.
2023-04-10 18:13:17,978 - numexpr.utils - INFO - NumExpr defaulting to 4 threads.
2023-04-10 18:13:18,303 - root - INFO - -2.618783614323712
2023-04-10 18:13:18,304 - root - INFO - corrcoef: 
0.9860095208474686   0.9175757164761829
2023-04-10 18:13:18,306 - root - INFO - regression coefficients:
[[ 1.11042346  0.10271851]
 [-0.09980373  0.98216601]]
2023-04-10 18:13:18,307 - root - INFO - regression intercept:
[-0.46769042 -0.32181783]
2023-04-10 18:13:20,211 - root - INFO - question:2 	 score:0.9481865284974094
2023-04-10 18:13:22,027 - root - INFO - question:3 	 score:0.1953259532595326
2023-04-10 18:13:24,041 - root - INFO - question:4 	 score:0.26083697688944407
2023-04-10 18:13:26,149 - root - INFO - question:5 	 score:0.3562375745526839
2023-04-10 18:13:28,134 - root - INFO - question:6 	 score:0.024356732450662003
2023-04-10 18:13:29,934 - root - INFO - question:7 	 score:0.3497376967274544
2023-04-10 18:13:31,839 - root - INFO - question:8 	 score:0.2743142144638404
2023-04-10 18:13:33,636 - root - INFO - question:9 	 score:0.30414688983262556
2023-04-10 18:13:35,505 - root - INFO - question:10 	 score:0.18073927555940167
2023-04-10 18:13:38,450 - root - INFO - question:11 	 score:0.28206732574145915
2023-04-10 18:13:41,545 - root - INFO - Plotting succeed.
2023-04-12 18:09:34,692 - numexpr.utils - INFO - NumExpr defaulting to 4 threads.
2023-04-12 18:09:34,935 - root - INFO - -2.78
2023-04-12 18:09:34,938 - root - INFO - corrcoef: 
0.9160400603005494   0.9286306468966671
2023-04-12 18:09:34,944 - root - INFO - regression coefficients:
[[ 1.1319863  -0.52246935]
 [ 0.0578849   0.98059347]]
2023-04-12 18:09:34,944 - root - INFO - regression intercept:
[0.50671885 0.08857221]
2023-04-12 18:09:34,948 - root - ERROR - Faild to open sklearn.txt from logger.error
Traceback (most recent call last):
  File "justscore_bySection_4urldata_final.py", line 356, in main
    img=plt.imread(str(designPth)+"1.png")         # reading backgram photos with png format
  File "D:\Anaconda3\lib\site-packages\matplotlib\pyplot.py", line 2246, in imread
    return matplotlib.image.imread(fname, format)
  File "D:\Anaconda3\lib\site-packages\matplotlib\image.py", line 1496, in imread
    with img_open(fname) as image:
  File "D:\Anaconda3\lib\site-packages\PIL\ImageFile.py", line 109, in __init__
    self.fp = open(fp, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './design1.png'
2023-04-12 18:10:50,610 - numexpr.utils - INFO - NumExpr defaulting to 4 threads.
2023-04-12 18:10:50,849 - root - INFO - -2.78
2023-04-12 18:10:50,851 - root - INFO - corrcoef: 
0.9160400603005494   0.9286306468966671
2023-04-12 18:10:50,853 - root - INFO - regression coefficients:
[[ 1.1319863  -0.52246935]
 [ 0.0578849   0.98059347]]
2023-04-12 18:10:50,854 - root - INFO - regression intercept:
[0.50671885 0.08857221]
2023-04-12 18:10:50,858 - root - ERROR - Faild to open sklearn.txt from logger.error
Traceback (most recent call last):
  File "justscore_bySection_4urldata_final.py", line 356, in main
    img=plt.imread(str(designPth)+"1.png")         # reading backgram photos with png format
  File "D:\Anaconda3\lib\site-packages\matplotlib\pyplot.py", line 2246, in imread
    return matplotlib.image.imread(fname, format)
  File "D:\Anaconda3\lib\site-packages\matplotlib\image.py", line 1496, in imread
    with img_open(fname) as image:
  File "D:\Anaconda3\lib\site-packages\PIL\ImageFile.py", line 109, in __init__
    self.fp = open(fp, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './design1.png'
2023-04-12 18:59:24,589 - numexpr.utils - INFO - NumExpr defaulting to 4 threads.
2023-04-12 18:59:25,502 - root - INFO - -2.78
2023-04-12 18:59:25,537 - root - INFO - corrcoef: 
0.9160400603005494   0.9286306468966671
2023-04-12 18:59:25,634 - root - INFO - regression coefficients:
[[ 1.1319863  -0.52246935]
 [ 0.0578849   0.98059347]]
2023-04-12 18:59:25,654 - root - INFO - regression intercept:
[0.50671885 0.08857221]
2023-04-12 18:59:25,686 - root - ERROR - Faild to open sklearn.txt from logger.error
Traceback (most recent call last):
  File "justscore_bySection_4urldata_final.py", line 357, in main
    img=plt.imread(str(designPth)+"1.png")         # reading backgram photos with png format
  File "D:\Anaconda3\lib\site-packages\matplotlib\pyplot.py", line 2246, in imread
    return matplotlib.image.imread(fname, format)
  File "D:\Anaconda3\lib\site-packages\matplotlib\image.py", line 1496, in imread
    with img_open(fname) as image:
  File "D:\Anaconda3\lib\site-packages\PIL\ImageFile.py", line 109, in __init__
    self.fp = open(fp, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './design1.png'
2023-04-12 19:12:44,111 - numexpr.utils - INFO - NumExpr defaulting to 4 threads.
2023-04-12 19:12:44,449 - root - INFO - -2.78
2023-04-12 19:12:44,451 - root - INFO - corrcoef: 
0.9160400603005494   0.9286306468966671
2023-04-12 19:12:44,453 - root - INFO - regression coefficients:
[[0.117293]]
2023-04-12 19:12:44,453 - root - INFO - regression coefficients:
[[0.11339196]]
2023-04-12 19:12:44,454 - root - INFO - regression intercept:
[0.41445397]
2023-04-12 19:12:44,455 - root - INFO - regression intercept:
[0.43465749]
2023-04-12 19:12:44,457 - root - ERROR - Faild to open sklearn.txt from logger.error
Traceback (most recent call last):
  File "justscore_bySection_4urldata_final.py", line 305, in main
    yy = model.predict(xx)
NameError: name 'model' is not defined
2023-04-12 19:14:11,728 - numexpr.utils - INFO - NumExpr defaulting to 4 threads.
2023-04-12 19:14:12,047 - root - INFO - -2.78
2023-04-12 19:14:12,048 - root - INFO - corrcoef: 
0.9160400603005494   0.9286306468966671
2023-04-12 19:14:12,053 - root - ERROR - Faild to open sklearn.txt from logger.error
Traceback (most recent call last):
  File "justscore_bySection_4urldata_final.py", line 287, in main
    model_x, model_y = correctDataEstimate(rec_trail)
  File "justscore_bySection_4urldata_final.py", line 215, in correctDataEstimate
    model_x.fit(x, bez_x); model_y.fit(y, bez_y)
  File "D:\Anaconda3\lib\site-packages\sklearn\linear_model\_base.py", line 505, in fit
    X, y = self._validate_data(X, y, accept_sparse=['csr', 'csc', 'coo'],
  File "D:\Anaconda3\lib\site-packages\sklearn\base.py", line 432, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "D:\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "D:\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 795, in check_X_y
    X = check_array(X, accept_sparse=accept_sparse,
  File "D:\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "D:\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 619, in check_array
    raise ValueError(
ValueError: Expected 2D array, got 1D array instead:
array=[-0.272 -0.264 -0.256 -0.256 -0.239 -0.231 -0.235 -0.213 -0.215 -0.214
 -0.213 -0.213 -0.214 -0.243 -0.127  0.397  0.394  0.393  0.373  0.435
  0.4    0.411  0.479  0.296  0.536  0.421  0.291  0.292  0.314  0.252
  0.32   0.274  0.275  0.289  0.288  0.245  0.28   0.264  0.313  0.311
  0.142 -0.256 -0.214 -0.188 -0.272 -0.271 -0.267 -0.229 -0.232 -0.231
 -0.227 -0.227 -0.238 -0.232 -0.24  -0.248 -0.239 -0.24   0.308  1.131
  1.858  2.003  1.992  1.992  1.965  1.92   1.916  1.887  1.864  1.873
  1.872  1.817  1.814  1.796  1.796  1.796  1.747  1.757  1.73   1.724
  1.704  1.64   1.64   1.614  1.623  1.62   1.593  1.586  1.585  1.568
  1.507  1.543  1.483  1.483  1.593  1.534  1.574  1.604  1.506  1.508
  1.464  1.469  1.454  1.425  1.401  1.372  1.372  1.367  1.372  1.319
  1.503  1.421  1.421  1.41   1.361  1.361  1.338  1.323  1.323  1.312
  1.304  1.202  1.197  1.192  1.192  1.191  1.163  1.16   1.12   1.102
  1.102  1.078  1.091  1.036  0.996  0.945  0.944  0.935  0.924  0.889
  0.822  0.82   0.819  0.775  0.775  0.687  0.727  0.659  0.659  0.677
  0.571  0.571  0.557  0.527  0.526  0.498  0.473  0.481  0.511  0.462
  0.462  0.479  0.475  0.396  0.41   0.396  0.397  0.438  0.306  0.309
  0.218  0.248  0.197  0.196  0.168  0.19   0.22   0.143  0.205  0.204
  0.186  0.172  0.183  0.204  0.18   0.181  0.192  0.164  0.171  0.121
  0.102  0.102  0.079  0.07   0.067 -0.004 -0.034  0.008  0.008 -0.01
  0.008  0.053 -0.036 -0.036 -0.05  -0.064  0.205 -1.861 -1.874 -1.888
 -1.895 -1.896 -1.844 -2.068 -2.029 -1.988 -1.943 -1.943 -2.303 -2.166
 -2.244 -2.261 -2.257 -2.266 -2.255 -2.253 -2.255 -2.268 -2.268 -2.337
 -2.315 -2.335 -2.314 -2.313 -2.375 -2.399 -2.412 -2.324 -2.347 -2.332
 -2.333 -2.391 -2.375 -2.383 -2.41  -2.458 -2.457 -2.424 -2.507 -2.476
 -2.485 -2.477 -2.476 -2.556 -2.536 -2.556 -2.556 -2.6   -2.601 -2.657
 -2.658 -2.654 -2.724 -2.69  -2.69  -2.675 -2.773 -2.742 -2.728 -2.731
 -2.72  -2.719 -2.767 -2.717 -2.681 -2.779 -2.78  -2.732 -2.714 -2.709
 -2.731 -2.746 -2.708 -2.707 -2.672 -2.683 -2.625 -2.653 -2.601 -2.601
 -2.6   -2.662 -2.666 -2.647 -2.646 -2.435 -2.338 -2.229 -2.264 -2.245
 -2.217 -2.217 -2.198 -2.113 -2.195 -2.174 -2.165 -2.166 -2.153 -2.124
 -2.114 -2.099 -2.075 -2.074 -2.036 -2.053 -2.152 -2.092 -2.079 -2.079
 -2.046 -1.987 -2.002 -1.95  -1.946 -1.947 -1.933 -1.992 -1.863 -1.905
 -1.924 -1.924 -1.894 -1.858 -1.86  -1.824 -1.799 -1.8   -1.799 -1.803
 -1.724 -1.715 -1.699 -1.644 -1.644 -1.676 -1.575 -1.6   -1.573 -1.529
 -1.529 -1.535 -1.565 -1.535 -1.469 -1.469 -1.458 -1.459 -1.419 -1.357
 -1.334 -1.309 -1.309 -1.324 -1.242 -1.273 -1.243 -1.211 -1.211 -1.193
 -1.19  -1.196 -1.181 -1.174 -1.175 -1.117 -1.111 -1.106 -1.081 -1.036
 -1.035 -1.073 -1.001 -0.967 -0.908 -0.907 -0.907 -0.872 -0.915 -0.459
 -0.174 -0.245 -0.245 -0.357 -0.377 -0.391 -0.424 -0.468 -0.432 -0.432
 -0.441 -0.415 -0.444 -0.426 -0.426 -0.392 -0.306 -0.439 -0.414 -0.353
 -0.344 -0.344 -0.272 -0.241 -0.22  -0.237 -0.137 -0.137 -0.149 -0.107
 -0.153 -0.054 -0.069 -0.069 -0.118 -0.013 -0.037 -0.034  0.011  0.01
 -0.159 -0.09  -0.118 -0.097 -0.113 -0.092 -0.092 -0.032 -0.033 -0.058
 -0.043 -0.042  0.028  0.031 -0.004  0.022  0.049  0.048  0.043  0.044
  0.045  0.034  0.232].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.
2023-04-12 19:14:45,331 - numexpr.utils - INFO - NumExpr defaulting to 4 threads.
2023-04-12 19:14:46,291 - root - INFO - -2.78
2023-04-12 19:14:46,337 - root - INFO - corrcoef: 
0.9160400603005494   0.9286306468966671
2023-04-12 19:14:46,419 - root - INFO - regression coefficients:
[[0.117293]]
2023-04-12 19:14:46,421 - root - INFO - regression coefficients:
[[0.11339196]]
2023-04-12 19:14:46,429 - root - INFO - regression intercept:
[0.41445397]
2023-04-12 19:14:46,465 - root - INFO - regression intercept:
[0.43465749]
2023-04-12 19:14:46,506 - root - ERROR - Faild to open sklearn.txt from logger.error
Traceback (most recent call last):
  File "justscore_bySection_4urldata_final.py", line 305, in main
    yy = model.predict(xx)
NameError: name 'model' is not defined
2023-04-12 19:17:17,286 - numexpr.utils - INFO - NumExpr defaulting to 4 threads.
2023-04-12 19:17:17,858 - root - INFO - -2.78
2023-04-12 19:17:17,862 - root - INFO - corrcoef: 
0.9160400603005494   0.9286306468966671
2023-04-12 19:17:17,884 - root - INFO - regression coefficients:
[[ 1.1319863  -0.52246935]
 [ 0.0578849   0.98059347]]
2023-04-12 19:17:17,906 - root - INFO - regression intercept:
[0.50671885 0.08857221]
2023-04-12 19:17:17,952 - root - ERROR - Faild to open sklearn.txt from logger.error
Traceback (most recent call last):
  File "justscore_bySection_4urldata_final.py", line 356, in main
    img=plt.imread(str(designPth)+"1.png")         # reading backgram photos with png format
  File "D:\Anaconda3\lib\site-packages\matplotlib\pyplot.py", line 2246, in imread
    return matplotlib.image.imread(fname, format)
  File "D:\Anaconda3\lib\site-packages\matplotlib\image.py", line 1496, in imread
    with img_open(fname) as image:
  File "D:\Anaconda3\lib\site-packages\PIL\ImageFile.py", line 109, in __init__
    self.fp = open(fp, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './design1.png'
2023-04-12 19:50:16,070 - numexpr.utils - INFO - NumExpr defaulting to 4 threads.
2023-04-12 19:50:16,285 - root - INFO - -2.78
2023-04-12 19:50:16,286 - root - INFO - corrcoef: 
0.9160400603005494   0.9286306468966671
2023-04-12 19:50:16,287 - root - INFO - regression coefficients:
[[ 1.1319863  -0.52246935]
 [ 0.0578849   0.98059347]]
2023-04-12 19:50:16,289 - root - INFO - regression intercept:
[0.50671885 0.08857221]
2023-04-12 19:50:16,294 - root - ERROR - Faild to open sklearn.txt from logger.error
Traceback (most recent call last):
  File "justscore_bySection_4urldata_final.py", line 356, in main
    img=plt.imread(str(designPth)+"1.png")         # reading backgram photos with png format
  File "D:\Anaconda3\lib\site-packages\matplotlib\pyplot.py", line 2246, in imread
    return matplotlib.image.imread(fname, format)
  File "D:\Anaconda3\lib\site-packages\matplotlib\image.py", line 1496, in imread
    with img_open(fname) as image:
  File "D:\Anaconda3\lib\site-packages\PIL\ImageFile.py", line 109, in __init__
    self.fp = open(fp, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './design1.png'
2023-04-13 11:17:45,009 - numexpr.utils - INFO - NumExpr defaulting to 4 threads.
2023-04-13 11:17:45,271 - root - INFO - -2.619596045638656
2023-04-13 11:17:45,274 - root - INFO - corrcoef: 
0.6971186800828615   0.10609777771574817
2023-04-13 11:17:45,275 - root - INFO - regression coefficients:
[[1 0]
 [0 1]]
2023-04-13 11:17:45,276 - root - INFO - regression intercept:
[0 0]
2023-04-13 11:17:45,282 - root - ERROR - Faild to open sklearn.txt from logger.error
Traceback (most recent call last):
  File "justscore_bySection_4urldata_final.py", line 356, in main
    img=plt.imread(str(designPth)+"1.png")         # reading backgram photos with png format
  File "D:\Anaconda3\lib\site-packages\matplotlib\pyplot.py", line 2246, in imread
    return matplotlib.image.imread(fname, format)
  File "D:\Anaconda3\lib\site-packages\matplotlib\image.py", line 1496, in imread
    with img_open(fname) as image:
  File "D:\Anaconda3\lib\site-packages\PIL\ImageFile.py", line 109, in __init__
    self.fp = open(fp, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './design1.png'
2023-04-13 11:17:58,459 - numexpr.utils - INFO - NumExpr defaulting to 4 threads.
2023-04-13 11:17:58,716 - root - INFO - -2.619596045638656
2023-04-13 11:17:58,716 - root - INFO - corrcoef: 
0.6971186800828615   0.10609777771574817
2023-04-13 11:17:58,717 - root - INFO - regression coefficients:
[[1 0]
 [0 1]]
2023-04-13 11:17:58,719 - root - INFO - regression intercept:
[0 0]
2023-04-13 11:17:59,907 - root - INFO - question:2 	 score:0.34886649874055414
2023-04-13 11:18:00,977 - root - INFO - question:3 	 score:0.03805839780384328
2023-04-13 11:18:02,166 - root - INFO - question:4 	 score:0.4021712003993012
2023-04-13 11:18:03,328 - root - INFO - question:5 	 score:0.0765
2023-04-13 11:18:04,454 - root - INFO - question:6 	 score:0.2373642830400599
2023-04-13 11:18:05,540 - root - INFO - question:7 	 score:0.220347456567929
2023-04-13 11:18:06,675 - root - INFO - question:8 	 score:0.43161966558522585
2023-04-13 11:18:07,735 - root - INFO - question:9 	 score:0.395875
2023-04-13 11:18:08,807 - root - INFO - question:10 	 score:0.43257092863392077
2023-04-13 11:18:09,884 - root - INFO - question:11 	 score:0.1354830646169229
2023-04-13 11:18:10,970 - root - INFO - Plotting succeed.
2023-04-13 12:33:25,194 - numexpr.utils - INFO - NumExpr defaulting to 4 threads.
2023-04-13 12:33:25,399 - root - ERROR - Faild to open sklearn.txt from logger.error
Traceback (most recent call last):
  File "justscore_bySection_4urldata_final.py", line 276, in main
    score,trail_level2 = measureFollowRate(tmpDf)
  File "justscore_bySection_4urldata_final.py", line 114, in measureFollowRate
    start_time = subDf['timestamp'].iat[0]/1000
  File "D:\Anaconda3\lib\site-packages\pandas\core\indexing.py", line 2103, in __getitem__
    return self.obj._get_value(*key, takeable=self._takeable)
  File "D:\Anaconda3\lib\site-packages\pandas\core\series.py", line 958, in _get_value
    return self._values[label]
IndexError: index 0 is out of bounds for axis 0 with size 0
2023-04-13 12:34:41,933 - numexpr.utils - INFO - NumExpr defaulting to 4 threads.
2023-04-13 12:34:42,143 - root - ERROR - Faild to open sklearn.txt from logger.error
Traceback (most recent call last):
  File "justscore_bySection_4urldata_final.py", line 276, in main
    score,trail_level2 = measureFollowRate(tmpDf)
  File "justscore_bySection_4urldata_final.py", line 114, in measureFollowRate
    start_time = subDf['timestamp'].iat[0]/1000
  File "D:\Anaconda3\lib\site-packages\pandas\core\indexing.py", line 2103, in __getitem__
    return self.obj._get_value(*key, takeable=self._takeable)
  File "D:\Anaconda3\lib\site-packages\pandas\core\series.py", line 958, in _get_value
    return self._values[label]
IndexError: index 0 is out of bounds for axis 0 with size 0
2023-04-13 12:37:54,063 - numexpr.utils - INFO - NumExpr defaulting to 4 threads.
2023-04-13 12:37:54,298 - root - ERROR - Faild to open sklearn.txt from logger.error
Traceback (most recent call last):
  File "justscore_bySection_4urldata_final.py", line 276, in main
    score,trail_level2 = measureFollowRate(tmpDf)
  File "justscore_bySection_4urldata_final.py", line 114, in measureFollowRate
    start_time = subDf['timestamp'].iat[0]/1000
  File "D:\Anaconda3\lib\site-packages\pandas\core\indexing.py", line 2103, in __getitem__
    return self.obj._get_value(*key, takeable=self._takeable)
  File "D:\Anaconda3\lib\site-packages\pandas\core\series.py", line 958, in _get_value
    return self._values[label]
IndexError: index 0 is out of bounds for axis 0 with size 0
2023-04-13 12:52:14,823 - numexpr.utils - INFO - NumExpr defaulting to 4 threads.
2023-04-13 12:52:15,035 - root - ERROR - Faild to open sklearn.txt from logger.error
Traceback (most recent call last):
  File "justscore_bySection_4urldata_final.py", line 277, in main
    score,trail_level2 = measureFollowRate(tmpDf)
  File "justscore_bySection_4urldata_final.py", line 115, in measureFollowRate
    start_time = subDf['timestamp'].iat[0]/1000
  File "D:\Anaconda3\lib\site-packages\pandas\core\indexing.py", line 2103, in __getitem__
    return self.obj._get_value(*key, takeable=self._takeable)
  File "D:\Anaconda3\lib\site-packages\pandas\core\series.py", line 958, in _get_value
    return self._values[label]
IndexError: index 0 is out of bounds for axis 0 with size 0
2023-04-13 12:54:11,438 - numexpr.utils - INFO - NumExpr defaulting to 4 threads.
2023-04-13 12:54:11,650 - root - ERROR - Faild to open sklearn.txt from logger.error
Traceback (most recent call last):
  File "justscore_bySection_4urldata_final.py", line 278, in main
    score,trail_level2 = measureFollowRate(tmpDf)
  File "justscore_bySection_4urldata_final.py", line 115, in measureFollowRate
    start_time = subDf['timestamp'].iat[0]/1000
  File "D:\Anaconda3\lib\site-packages\pandas\core\indexing.py", line 2103, in __getitem__
    return self.obj._get_value(*key, takeable=self._takeable)
  File "D:\Anaconda3\lib\site-packages\pandas\core\series.py", line 958, in _get_value
    return self._values[label]
IndexError: index 0 is out of bounds for axis 0 with size 0
2023-04-13 12:55:36,892 - numexpr.utils - INFO - NumExpr defaulting to 4 threads.
2023-04-13 12:55:37,147 - root - INFO - -2.6179651608320005
2023-04-13 12:55:37,148 - root - INFO - corrcoef: 
0.7286394659113814   0.7286950408350515
2023-04-13 12:55:37,150 - root - INFO - regression coefficients:
[[1 0]
 [0 1]]
2023-04-13 12:55:37,151 - root - INFO - regression intercept:
[0 0]
2023-04-13 12:55:37,155 - root - ERROR - Faild to open sklearn.txt from logger.error
Traceback (most recent call last):
  File "justscore_bySection_4urldata_final.py", line 358, in main
    img=plt.imread(str(designPth)+"1.png")         # reading backgram photos with png format
  File "D:\Anaconda3\lib\site-packages\matplotlib\pyplot.py", line 2246, in imread
    return matplotlib.image.imread(fname, format)
  File "D:\Anaconda3\lib\site-packages\matplotlib\image.py", line 1496, in imread
    with img_open(fname) as image:
  File "D:\Anaconda3\lib\site-packages\PIL\ImageFile.py", line 109, in __init__
    self.fp = open(fp, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './design1.png'
2023-04-13 12:55:51,590 - numexpr.utils - INFO - NumExpr defaulting to 4 threads.
2023-04-13 12:55:51,846 - root - INFO - -2.6179651608320005
2023-04-13 12:55:51,847 - root - INFO - corrcoef: 
0.7286394659113814   0.7286950408350515
2023-04-13 12:55:51,848 - root - INFO - regression coefficients:
[[1 0]
 [0 1]]
2023-04-13 12:55:51,849 - root - INFO - regression intercept:
[0 0]
2023-04-13 12:55:52,928 - root - INFO - question:2 	 score:0.33695652173913043
2023-04-13 12:55:53,905 - root - INFO - question:3 	 score:0.03284215784215784
2023-04-13 12:55:55,070 - root - INFO - question:4 	 score:0.9965021861336665
2023-04-13 12:55:56,265 - root - INFO - question:5 	 score:0.9475458973398276
2023-04-13 12:55:57,409 - root - INFO - question:6 	 score:0.925421611492817
2023-04-13 12:55:58,524 - root - INFO - question:7 	 score:0.749531542785759
2023-04-13 12:55:59,676 - root - INFO - question:8 	 score:0.8191130543410369
2023-04-13 12:56:00,739 - root - INFO - question:9 	 score:0.4344241818636023
2023-04-13 12:56:01,805 - root - INFO - question:10 	 score:0.9722707969023232
2023-04-13 12:56:02,825 - root - INFO - question:11 	 score:0.7454954954954955
2023-04-13 12:56:03,885 - root - INFO - Plotting succeed.
2023-04-13 13:55:42,393 - numexpr.utils - INFO - NumExpr defaulting to 4 threads.
2023-04-13 13:55:42,636 - root - INFO - -2.619596045638656
2023-04-13 13:55:42,637 - root - INFO - corrcoef: 
0.6971186800828615   0.10609777771574817
2023-04-13 13:55:42,638 - root - INFO - regression coefficients:
[[1 0]
 [0 1]]
2023-04-13 13:55:42,639 - root - INFO - regression intercept:
[0 0]
2023-04-13 13:55:43,683 - root - INFO - question:2 	 score:0.34886649874055414
2023-04-13 13:55:44,640 - root - INFO - question:3 	 score:0.03805839780384328
2023-04-13 13:55:45,669 - root - INFO - question:4 	 score:0.4021712003993012
2023-04-13 13:55:46,728 - root - INFO - question:5 	 score:0.0765
2023-04-13 13:55:47,739 - root - INFO - question:6 	 score:0.2373642830400599
2023-04-13 13:55:48,736 - root - INFO - question:7 	 score:0.220347456567929
2023-04-13 13:55:49,787 - root - INFO - question:8 	 score:0.43161966558522585
2023-04-13 13:55:50,820 - root - INFO - question:9 	 score:0.395875
2023-04-13 13:55:51,869 - root - INFO - question:10 	 score:0.43257092863392077
2023-04-13 13:55:52,911 - root - INFO - question:11 	 score:0.1354830646169229
2023-04-13 13:55:54,000 - root - INFO - Plotting succeed.
2023-04-13 13:56:54,923 - numexpr.utils - INFO - NumExpr defaulting to 4 threads.
2023-04-13 13:56:55,159 - root - INFO - -2.6179651608320005
2023-04-13 13:56:55,160 - root - INFO - corrcoef: 
0.7286394659113814   0.7286950408350515
2023-04-13 13:56:55,162 - root - INFO - regression coefficients:
[[1 0]
 [0 1]]
2023-04-13 13:56:55,162 - root - INFO - regression intercept:
[0 0]
2023-04-13 13:56:56,216 - root - INFO - question:2 	 score:0.33695652173913043
2023-04-13 13:56:57,164 - root - INFO - question:3 	 score:0.03284215784215784
2023-04-13 13:56:58,284 - root - INFO - question:4 	 score:0.9965021861336665
2023-04-13 13:56:59,426 - root - INFO - question:5 	 score:0.9475458973398276
2023-04-13 13:57:00,504 - root - INFO - question:6 	 score:0.925421611492817
2023-04-13 13:57:01,531 - root - INFO - question:7 	 score:0.749531542785759
2023-04-13 13:57:02,555 - root - INFO - question:8 	 score:0.8191130543410369
2023-04-13 13:57:03,553 - root - INFO - question:9 	 score:0.4344241818636023
2023-04-13 13:57:04,577 - root - INFO - question:10 	 score:0.9722707969023232
2023-04-13 13:57:05,585 - root - INFO - question:11 	 score:0.7454954954954955
2023-04-13 13:57:06,585 - root - INFO - Plotting succeed.
2023-04-13 14:14:32,152 - numexpr.utils - INFO - NumExpr defaulting to 4 threads.
2023-04-13 14:14:32,389 - root - INFO - -2.6179651608320005
2023-04-13 14:14:32,391 - root - INFO - corrcoef: 
0.7286394659113814   0.7286950408350515
2023-04-13 14:14:32,392 - root - INFO - regression coefficients:
[[1 0]
 [0 1]]
2023-04-13 14:14:32,393 - root - INFO - regression intercept:
[0 0]
2023-04-13 14:14:33,435 - root - INFO - question:2 	 score:0.33695652173913043
2023-04-13 14:14:34,393 - root - INFO - question:3 	 score:0.03284215784215784
2023-04-13 14:14:35,457 - root - INFO - question:4 	 score:0.9965021861336665
2023-04-13 14:14:36,552 - root - INFO - question:5 	 score:0.9475458973398276
2023-04-13 14:14:37,556 - root - INFO - question:6 	 score:0.925421611492817
2023-04-13 14:14:38,548 - root - INFO - question:7 	 score:0.749531542785759
2023-04-13 14:14:39,581 - root - INFO - question:8 	 score:0.8191130543410369
2023-04-13 14:14:40,572 - root - INFO - question:9 	 score:0.4344241818636023
2023-04-13 14:14:41,593 - root - INFO - question:10 	 score:0.9722707969023232
2023-04-13 14:14:42,593 - root - INFO - question:11 	 score:0.7454954954954955
2023-04-13 14:14:43,616 - root - INFO - Plotting succeed.
